server:
  port: 8250
spring:
  application:
    name: iot-cloud-device
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true

# MyBatis-Plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  typeAliasesPackage: com.iot